# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eeb1f31a25b050166197abf20116915cfa2c3f7fdb4989fd81defaec4af6696ab11fb264d459c3a028ec56c34228b4bd68db4f51b25559273f589d09643f023

test:
  secret_key_base: cc0c2e6b0475cbedae1ddea6b28d8fb8f558271f6e829f679a8c950d4aba3ec7e3bb8a51da3f1aca2744a571f962bb4d3ac12a697e9f5a54dfae49ce46cd2a7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
